# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'win1803'

strategy:
  parallel: 10

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '^10.10.0'
  displayName: 'Install Node.js'

- script: |
    yarn
  displayName: 'Install dependencies'

- script: |
    yarn build
  displayName: 'Build Nuxt'

- script: |
    yarn test:fixtures -w=2
  displayName: 'Test: Build Fixtures'

- script: |
    yarn test:unit -w=2
  displayName: 'Test: Run unit tests'
