blank_issues_enabled: false
contact_links:
  - name: ğŸš¨ Bug report | Bug æäº¤
    url: https://bug.nuxtjs.org/
    about: |
      Please report bugs here.
      è¯·åœ¨æ­¤æäº¤ Bugã€‚
  - name: ğŸ™‹ Feature request | æ–°åŠŸèƒ½ææ¡ˆ
    url: https://feature.nuxtjs.org/
    about: |
      Please request features here.
      è¯·åœ¨æ­¤æäº¤æ–°åŠŸèƒ½ææ¡ˆã€‚
  - name: ğŸ¤” Consulting from the Nuxt team | å’¨è¯¢ Nuxt å›¢é˜Ÿ
    url: https://otechie.com/nuxt
    about: |
      Get technical support, project audits, app deployments, and custom development from the core Nuxt.js team.
      å’¨è¯¢æ ¸å¿ƒ Nuxt.js å›¢é˜Ÿä»¥è·å¾—æŠ€æœ¯æ”¯æŒï¼Œé¡¹ç›®å®¡æ ¸ï¼Œåº”ç”¨ç¨‹åºéƒ¨ç½²ä»¥åŠè‡ªå®šä¹‰å¼€å‘ç­‰æ–¹é¢ä¸Šçš„å¸®åŠ©ã€‚
  - name: â—ï¸ All other issues | å…¶ä»–é—®é¢˜
    url: https://cmty.nuxtjs.org/
    about: |
      Please create all other issues here.
      è¯·åœ¨æ­¤åˆ›å»ºå…¶ä»–ç±»å‹é—®é¢˜ã€‚
