name: docs

on:
  pull_request:
    paths:
      - 'docs/**'
      - '*.md'
    branches:
      - main
      - 3.x

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/tutorials/authenticate-with-github_token
permissions: {}

jobs:
  link-checker:
    runs-on: ubuntu-24.04-arm
    steps:
      # Cache lychee results (e.g. to avoid hitting rate limits)
      - name: Restore lychee cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      # check links with Lychee
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lychee link checker
        uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0 # v2.7.0
        with:
          # arguments with file types to check
          args: >-
            '-c=lychee.toml'
            './docs/**/*.md'
            './docs/**/*.html'
            './packages/*/src/**/*.ts'
            './packages/*/src/**/*.js'
            './packages/*/src/**/*.md'
          # fail the action on broken links
          fail: true
        env:
          # to be used in case rate limits are surpassed
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
