name: bridge
on:
  pull_request:
    types: [closed]
    paths:
      - "packages/nuxt/src/app/composables/**"

permissions: {}

jobs:
  notify:
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        repo: ["nuxt/bridge"]
    runs-on: ubuntu-latest
    steps:
      - name: repository dispatch
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.BRIDGE_GITHUB_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: port-upstream
          client-payload: '{"url": "${{ github.event.pull_request.html_url }}"}'
