name: nuxt2-nightly

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

# https://github.com/vitejs/vite/blob/main/.github/workflows/ci.yml
env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

permissions:
  contents: read

jobs:
  nightly:
    if: github.repository_owner == 'nuxt'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: '2.x'
          fetch-depth: 0 # All history
      - name: fetch tags
        run: git fetch --depth=1 origin "+refs/tags/*:refs/tags/*"
      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: install
        run: yarn --check-files --frozen-lockfile --non-interactive
      - name: lint
        run: yarn test:lint
      - name: audit
        run: yarn run audit
      - name: build
        run: yarn test:fixtures -i
      - name: lint app
        run: yarn lint:app
      - name: test types
        run: yarn test:types
      - name: test dev
        run: yarn test:dev
      - name: test unit
        run: yarn test:unit
      - name: test e2e
        run: yarn test:e2e
      - name: bump version
        run: yarn lerna version --yes --no-changelog --no-git-tag-version --no-push --force-publish "*" --loglevel verbose
      - name: build
        run: PACKAGE_SUFFIX=edge yarn build
      - name: publish
        run: ./scripts/workspace-run npm publish -q
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
          NPM_CONFIG_PROVENANCE: true

