name: triage

on:
  issues:
    types: [edited]

concurrency:
  group: llm-triage-edit-${{ github.event.issue.number }}
  # avoid losing analysis if user edits rapidly
  cancel-in-progress: false

jobs:
  triage:
    uses: nuxt/.github/.github/workflows/triage-edited.yml@b3b9f7dac45b3dbaaac266077f01690ea61e4137
    permissions:
      contents: read
      issues: write
      models: read
