name: triage

on:
  issues:
    types: [labeled]

jobs:
  transfer-spam:
    if: github.event.label.name == 'spam'
    uses: nuxt/.github/.github/workflows/triage-spam-transfer.yml@b3b9f7dac45b3dbaaac266077f01690ea61e4137
    with:
      spam-repo-id: ${{ vars.TRIAGE_SPAM_REPO_ID }}
    permissions:
      issues: write
